name: Build and Deploy Resume

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Build with Gradle
        run: ./gradlew build

      - name: Start Spring Boot app
        run: nohup java -jar build/libs/resume.jar &

      - name: Wait for app to start
        run: sleep 15

      - name: Create docs directory
        run: mkdir -p docs

      - name: Fetch generated HTML from API
        run: curl http://localhost:8080/resume/html -o docs/index.html

      - name: Disable Jekyll
        run: touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs