name: Build and Deploy Resume

on:
  push:
    branches:
      - main  # 본인 기본 브랜치 이름으로 수정하세요

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Spring Boot app
        run: ./gradlew bootJar

      - name: Start Spring Boot app in background
        run: |
          nohup java -jar build/libs/*.jar & 
          echo $! > springboot.pid
        # 백그라운드 실행 PID 저장

      - name: Wait for Spring Boot to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/resume/html > /dev/null; then
              echo "Spring Boot is up!"
              break
            else
              echo "Waiting for Spring Boot... $i"
              sleep 2
            fi
          done

      - name: Fetch generated HTML
        run: |
          curl http://localhost:8080/resume/html -o docs/index.html
          echo "==== docs/index.html content ===="
          head -20 docs/index.html

      - name: Create .nojekyll file
        run: echo "" > docs/.nojekyll

      - name: Check docs folder contents
        run: ls -l docs

      - name: Stop Spring Boot app
        run: |
          kill $(cat springboot.pid)

      - name: Configure Git
        run: |
          git config user.name "w-garden"
          git config user.email "w.garden316@gmail.com"

      - name: Commit and push docs
        run: |
          git add docs/
          git status
          git commit -m
