name: Build and Deploy Resume

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot app (bootJar)
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      - name: Start Spring Boot app in background
        run: |
          nohup java -jar build/libs/*.jar --server.port=8080 > server.log 2>&1 &

      - name: Wait until server is ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/resume/html; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server... ($i)"
            sleep 2
          done
          echo "Server did not start in time. Showing logs:"
          cat server.log || echo "No logs found"
          exit 1

      - name: Create docs directory
        run: mkdir -p docs

      - name: Fetch generated HTML from API
        run: curl http://localhost:8080/resume/html -o docs/index.html

      - name: Show server logs (for debugging)
        if: always()
        run: cat server.log || echo "No logs"


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
